language: csharp
env:  
  - CLI_VERSION=latest
sudo: required
dist: trusty
mono:
  - latest
dotnet: 1.0.1
os:  
  - linux
script:
  - ./buildAndTest.sh
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7a42163c2ddadec5e6b5
    on_success: change
    on_failure: always
    on_start: false
