language: csharp
sudo: required
dist: trusty
mono:
  - latest
dotnet: 2.0.0
os:  
  - linux
script:
  - ./build.sh
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7a42163c2ddadec5e6b5
    on_success: change
    on_failure: always
    on_start: false
