language: csharp
env:  
  - CLI_VERSION=latest
sudo: required
dist: trusty
mono:
  - latest
dotnet: 1.0.0-preview2-003131
os:  
  - linux
script:
  - ./buildAndTest.sh
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/604ccf4d6e9f68343ff8
    on_success: change
    on_failure: always
    on_start: false
