version: '1.0.{build}'
configuration:
- Debug
- Release
platform: Any CPU
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- appveyor-retry dotnet restore zipkin4net.dotnetcore.sln --verbosity Minimal
build_script:
- dotnet build "zipkin4net.dotnetcore.sln" -c %CONFIGURATION% --version-suffix %LABEL%
after_build:
- dotnet pack "zipkin4net.dotnetcore.sln" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
test_script:
- dotnet test "Src/zipkin4net/Tests/zipkin4net.Tests.dotnetcore.csproj" -c %CONFIGURATION%
- dotnet test "Src/zipkin4net.middleware.owin/Tests/zipkin4net.middleware.owin.Tests.dotnetcore.csproj" -c %CONFIGURATION%
cache:
- '%USERPROFILE%\.nuget\packages'
